# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album_Producer',
            fields=[
                ('albumident', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('copyright', models.DateField()),
                ('speed', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('instrld', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Lives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('ssn', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Performs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('address', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays_instrld_instruments', to='notownapp.Instruments')),
                ('ssn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Musicians')),
            ],
        ),
        migrations.CreateModel(
            name='SongAppears',
            fields=[
                ('songID', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('albumident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Album_Producer')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_author_musicians', to='notownapp.Musicians')),
                ('performs', models.ManyToManyField(through='notownapp.Performs', to='notownapp.Musicians')),
            ],
        ),
        migrations.CreateModel(
            name='Telephone_Home',
            fields=[
                ('phone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Places')),
            ],
        ),
        migrations.AddField(
            model_name='performs',
            name='songID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perform_songID_song', to='notownapp.SongAppears'),
        ),
        migrations.AddField(
            model_name='performs',
            name='ssn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Musicians'),
        ),
        migrations.AddField(
            model_name='lives',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Places'),
        ),
        migrations.AddField(
            model_name='lives',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Telephone_Home'),
        ),
        migrations.AddField(
            model_name='lives',
            name='ssn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Musicians'),
        ),
        migrations.AddField(
            model_name='instruments',
            name='plays',
            field=models.ManyToManyField(through='notownapp.Plays', to='notownapp.Musicians'),
        ),
        migrations.AddField(
            model_name='album_producer',
            name='ssn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Musicians'),
        ),
        migrations.AlterUniqueTogether(
            name='plays',
            unique_together=set([('ssn', 'instrld')]),
        ),
        migrations.AlterUniqueTogether(
            name='performs',
            unique_together=set([('ssn', 'songID')]),
        ),
        migrations.AlterUniqueTogether(
            name='lives',
            unique_together=set([('ssn', 'address')]),
        ),
    ]
