# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notownapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('instrld', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Instruments')),
            ],
        ),
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('ssn', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('address', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SongAppears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Telephone_Home',
            fields=[
                ('phone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Places')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='membership',
            name='ssn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Musicians'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('ssn', 'instrld')]),
        ),
    ]
