# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notownapp', '0002_auto_20161026_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='plays',
            field=models.ManyToManyField(through='notownapp.Membership', to='notownapp.Musicians'),
        ),
    ]
