# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notownapp', '0003_instruments_plays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='instrld',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='ssn',
        ),
        migrations.AlterField(
            model_name='instruments',
            name='plays',
            field=models.ManyToManyField(through='notownapp.Plays', to='notownapp.Musicians'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.AddField(
            model_name='plays',
            name='instrld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playdata', to='notownapp.Instruments'),
        ),
        migrations.AddField(
            model_name='plays',
            name='ssn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Musicians'),
        ),
        migrations.AlterUniqueTogether(
            name='plays',
            unique_together=set([('ssn', 'instrld')]),
        ),
    ]
