# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notownapp', '0004_auto_20161028_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_Producer',
            fields=[
                ('albumident', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('copyright', models.DateField()),
                ('speed', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('ssn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Musicians')),
            ],
        ),
        migrations.CreateModel(
            name='Performs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='songappears',
            name='id',
        ),
        migrations.AddField(
            model_name='songappears',
            name='author',
            field=models.CharField(default='ayush', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songappears',
            name='title',
            field=models.CharField(default='book', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songappears',
            name='songID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telephone_home',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Places'),
        ),
        migrations.AddField(
            model_name='performs',
            name='songID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songid', to='notownapp.SongAppears'),
        ),
        migrations.AddField(
            model_name='performs',
            name='ssn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Musicians'),
        ),
        migrations.AddField(
            model_name='songappears',
            name='albumident',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='notownapp.Album_Producer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songappears',
            name='performs',
            field=models.ManyToManyField(through='notownapp.Performs', to='notownapp.Musicians'),
        ),
        migrations.AlterUniqueTogether(
            name='performs',
            unique_together=set([('ssn', 'songID')]),
        ),
    ]
