# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notownapp', '0005_auto_20161029_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Places')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Telephone_Home')),
                ('ssn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Musicians')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lives',
            unique_together=set([('ssn', 'address')]),
        ),
    ]
