# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notownapp', '0006_auto_20161029_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lives',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Places'),
        ),
        migrations.AlterField(
            model_name='lives',
            name='phone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notownapp.Telephone_Home'),
        ),
    ]
