# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notownapp', '0008_auto_20161029_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songappears',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicianname', to='notownapp.Musicians'),
        ),
    ]
