# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notownapp', '0010_auto_20161116_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songappears',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='notownapp.Musicians'),
        ),
    ]
