# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notownapp', '0011_auto_20161116_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performs',
            name='songID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perform_songID_song', to='notownapp.SongAppears'),
        ),
        migrations.AlterField(
            model_name='plays',
            name='instrld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays_instrld_instruments', to='notownapp.Instruments'),
        ),
        migrations.AlterField(
            model_name='songappears',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_author_musicians', to='notownapp.Musicians'),
        ),
    ]
