# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notownapp', '0015_auto_20161127_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='address',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
