# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notownapp', '0016_auto_20161127_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='address',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telephone_home',
            name='phone',
            field=models.IntegerField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
