# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notownapp', '0017_auto_20161127_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephone_home',
            name='phone',
            field=models.BigIntegerField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
